services:

  postgres:
    image: postgres:17-alpine

  cleanarchitecture-api:
    image: ${DOCKER_REGISTRY-}cleanarchitecture-api:latest
    build:
      context: .
      dockerfile: CleanArchitecture.API/Dockerfile

  cleanarchitecture-jobs:
    image: ${DOCKER_REGISTRY-}cleanarchitecture-jobs:latest
    build:
      context: .
      dockerfile: CleanArchitecture.Jobs/Dockerfile

volumes:
  postgres_data: {}
